### ISSUE TITLE
Lỗi  "No 'Access-Control-Allow-Origin' header is present on the requested resource"

### ISSUE THREAD

**Issue by earthnoob** [fongfan999/uit_es_creator#1]
Khi cố gắng thực hiện phương thức GET bằng thư viện Axios cho ReactJS, mình đã vướng phải lỗi `"No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access."`.

Đây là đoạn code đã gây ra lỗi: `axios.get('https://uesc.foxfizz.com/api/v1/daa/uesc.json?student_id=16521090')`. Tuy nhiên phía server vẫn trả về cho client đầy đủ thông tin (200 OK).

Đây là response headers nhận được sau khi mình gửi yêu cầu:
`Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Date: Tue, 31 Jul 2018 14:33:33 GMT
ETag: W/"68cc01098f49c24d612f84e45b58fab0"
Server: nginx
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 0e1eb2fa-42bc-4635-a530-599647bc26f2
X-Runtime: 0.008599
X-XSS-Protection: 1; mode=block`

Và đây là request headers:
`Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: vi,en;q=0.9
Connection: keep-alive
DNT: 1
Host: uesc.foxfizz.com
If-None-Match: W/"68cc01098f49c24d612f84e45b58fab0"
Origin: http://localhost:8080
Referer: http://localhost:8080/
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 YaBrowser/18.6.1.770 Yowser/2.5 Safari/537.36`

Mình tin rằng lỗi phát sinh do việc backend chưa đặt 'Access-Control-Allow-Origin' làm header phản hồi khi client gửi yêu cầu. Nếu API của bạn có setup CORS thì cho mình biết.

**Comment by fongfan999** [comment]
Hi @echoscp,
The issue has been resolved 💯
